import type { SavedSession } from '../types'

function escapeMarkdown(text: string): string {
  // Escape Markdown special characters; handle backslash first to avoid double-escaping
  return text.replace(/\\/g, '\\\\').replace(/([`*_{}[\]<>()#+\-.!|])/g, '\\$1')
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

export function buildMarkdown(session: SavedSession): string {
  const { summary } = session
  const { inference } = summary
  const lines: string[] = []

  // Header
  lines.push(`# ${escapeMarkdown(session.title)}`)
  lines.push('')
  lines.push(`> **Date:** ${formatDate(session.createdAt)}  `)
  lines.push(`> **Duration:** ${session.duration}  `)
  lines.push(`> **Slides:** ${session.slideCount}  `)
  lines.push(`> **Captures:** ${session.totalCaptures}  `)
  lines.push(`> **Avg Confidence:** ${session.avgConfidence.toFixed(0)}%`)
  lines.push('')

  // Inferred Narrative
  if (inference.narrative) {
    lines.push('## 🧠 Inferred Summary')
    lines.push('')
    lines.push(inference.narrative)
    lines.push('')
  }

  // Overview Stats
  lines.push('## 📊 Overview')
  lines.push('')
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Content Type | ${inference.contentTypeLabel} |`)
  lines.push(`| Slides / Screens | ${summary.slideCount} |`)
  lines.push(`| Total Captures | ${summary.totalCaptures} |`)
  lines.push(`| Words | ${summary.wordCount.toLocaleString()} |`)
  lines.push(`| Duration | ${summary.duration} |`)
  lines.push(`| Avg Confidence | ${summary.avgConfidence.toFixed(0)}% |`)
  if (summary.languages.length > 0) {
    lines.push(`| Languages | ${summary.languages.join(', ')} |`)
  }
  lines.push('')

  // Action Items
  if (inference.actionItems.length > 0) {
    lines.push('## ✅ Action Items')
    lines.push('')
    for (const item of inference.actionItems) {
      lines.push(`- [ ] ${item}`)
    }
    lines.push('')
  }

  // Key Points
  if (inference.keySentences.length > 0) {
    lines.push('## 💡 Key Points')
    lines.push('')
    for (const s of inference.keySentences) {
      lines.push(`- ${s}`)
    }
    lines.push('')
  }

  // Headings
  if (inference.headings.length > 0) {
    lines.push('## 📑 Detected Headings')
    lines.push('')
    for (const h of inference.headings) {
      lines.push(`- ${escapeMarkdown(h)}`)
    }
    lines.push('')
  }

  // Entities / named mentions
  if (summary.properNouns.length > 0) {
    lines.push('## 👤 Named Entities')
    lines.push('')
    lines.push(summary.properNouns.map(n => `\`${n}\``).join(' · '))
    lines.push('')
  }

  // Keywords
  if (summary.keywords.length > 0) {
    lines.push('## 🏷️ Key Topics')
    lines.push('')
    lines.push(summary.keywords.map(k => `\`${k}\``).join(' · '))
    lines.push('')
  }

  // Extracted contact info / URLs
  if (summary.emails.length > 0) {
    lines.push('## 📧 Emails')
    lines.push('')
    for (const e of summary.emails) {
      lines.push(`- ${e}`)
    }
    lines.push('')
  }
  if (summary.urls.length > 0) {
    lines.push('## 🔗 URLs')
    lines.push('')
    for (const u of summary.urls) {
      lines.push(`- <${u}>`)
    }
    lines.push('')
  }
  if (summary.phones.length > 0) {
    lines.push('## 📞 Phone Numbers')
    lines.push('')
    for (const p of summary.phones) {
      lines.push(`- ${p}`)
    }
    lines.push('')
  }

  // Per-Slide Breakdown
  if (summary.slides.length > 0) {
    lines.push('## 📄 Slide Breakdown')
    lines.push('')
    for (const slide of summary.slides) {
      lines.push(`### Slide ${slide.slideNumber}`)
      lines.push('')
      if (slide.keywords.length > 0) {
        lines.push(`**Keywords:** ${slide.keywords.join(', ')}`)
        lines.push('')
      }
      lines.push('```')
      lines.push(slide.text)
      lines.push('```')
      if (slide.urls.length > 0) {
        lines.push('')
        lines.push(`**URLs:** ${slide.urls.map(u => `<${u}>`).join(', ')}`)
      }
      if (slide.emails.length > 0) {
        lines.push('')
        lines.push(`**Emails:** ${slide.emails.join(', ')}`)
      }
      lines.push('')
    }
  }

  // Full Captured Text
  lines.push('## 📝 Full Captured Text')
  lines.push('')
  lines.push('```')
  lines.push(summary.fullText)
  lines.push('```')
  lines.push('')

  // Footer
  lines.push('---')
  lines.push('*Generated by ScreenShare Transcribe — all processing is local, no data leaves your device.*')

  return lines.join('\n')
}

export function buildJSON(session: SavedSession): string {
  return JSON.stringify(session, null, 2)
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50)
}

export function downloadMarkdown(session: SavedSession): void {
  const content = buildMarkdown(session)
  // Include a short ID suffix to avoid collisions between same-title same-day sessions
  const idSuffix = session.id.slice(0, 6)
  const filename = `${slugify(session.title)}-${new Date(session.createdAt).toISOString().slice(0, 10)}-${idSuffix}.md`
  downloadFile(content, filename, 'text/markdown;charset=utf-8')
}

export function downloadJSON(session: SavedSession): void {
  const content = buildJSON(session)
  const idSuffix = session.id.slice(0, 6)
  const filename = `${slugify(session.title)}-${new Date(session.createdAt).toISOString().slice(0, 10)}-${idSuffix}.json`
  downloadFile(content, filename, 'application/json;charset=utf-8')
}

export async function copyMarkdownToClipboard(session: SavedSession): Promise<void> {
  const content = buildMarkdown(session)
  await navigator.clipboard.writeText(content)
}
